package com.github.fcat97.unionkt.serialization.kotlinx

import com.github.fcat97.unionkt.api.UnionInfo
import com.github.fcat97.unionkt.api.UnionMemberInfo
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.squareup.kotlinpoet.ANY
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Emits `<Union>Serializer`: an `object` for a plain union, a class taking one
 * `KSerializer` per type parameter for a generic one.
 *
 * Serializing writes the case's inner value only. Deserializing reads a `JsonElement`,
 * keeps the cases whose descriptor kind can produce that JSON shape, and tries them in
 * declaration order; the first that decodes wins.
 *
 * Every multi-token expression in the emitted code sits inside parentheses: KotlinPoet may
 * wrap long lines at any space, and Kotlin ignores line breaks only inside brackets.
 */
internal class SerializerWriter(private val codeGenerator: CodeGenerator) {

    fun write(union: UnionInfo) {
        val serializerType = serializerClassName(union)
        val typeVariables = union.typeParameters.map { TypeVariableName(it.name, it.bounds) }
        val unionType: TypeName =
            if (typeVariables.isEmpty()) union.unionType
            else union.unionType.parameterizedBy(typeVariables.map { TypeVariableName(it.name) })

        val type = if (typeVariables.isEmpty()) {
            TypeSpec.objectBuilder(serializerType)
        } else {
            TypeSpec.classBuilder(serializerType)
                .addTypeVariables(typeVariables)
                .primaryConstructor(
                    FunSpec.constructorBuilder().apply {
                        typeVariables.forEach { addParameter(parameterSerializerName(it.name), serializerOf(TypeVariableName(it.name))) }
                    }.build(),
                )
                .apply {
                    typeVariables.forEach {
                        val name = parameterSerializerName(it.name)
                        addProperty(
                            PropertySpec.builder(name, serializerOf(TypeVariableName(it.name)), KModifier.PRIVATE)
                                .initializer(name)
                                .build(),
                        )
                    }
                }
        }

        type.addModifiers(union.visibility)
            .addAnnotation(AnnotationSpec.builder(OPT_IN).addMember("%T::class", EXPERIMENTAL_API).build())
            .addSuperinterface(serializerOf(unionType))
            .addKdoc(
                "Untagged JSON serializer for [%T], generated by unionKt from [%L].\n\n" +
                    "Writes a case's inner value. Reads by keeping the cases whose kind matches the " +
                    "JSON shape, then trying them in declaration order.",
                union.unionType,
                union.markerName,
            )

        union.members.filter { it.typeParameterName == null }.forEach { member ->
            type.addProperty(
                PropertySpec.builder(serializerReference(member), serializerOf(member.typeName), KModifier.PRIVATE)
                    .initializer("%M<%T>()", SERIALIZER_FUNCTION, member.typeName)
                    .build(),
            )
        }

        type.addProperty(
            PropertySpec.builder("descriptor", SERIAL_DESCRIPTOR, KModifier.OVERRIDE)
                // CONTEXTUAL kind: a union can be any JSON shape, so an outer union's shape
                // filter must always try it.
                .initializer(
                    "%M(%S, %T(%T::class).descriptor)",
                    SERIAL_DESCRIPTOR_FUNCTION,
                    union.unionType.canonicalName,
                    CONTEXTUAL_SERIALIZER,
                    ANY,
                )
                .build(),
        )
        type.addFunction(serialize(union, unionType))
        type.addFunction(deserialize(union, unionType, serializerType))
        type.addFunction(accepts())
        type.addFunction(noMatch(union))

        FileSpec.builder(serializerType)
            .addFileComment("Generated by unionKt serialization-kotlinx from @Union on %L. Do not edit.", union.markerName)
            .addType(type.build())
            .build()
            .writeTo(codeGenerator, Dependencies(aggregating = false, *union.sources.toTypedArray()))
    }

    private fun serialize(union: UnionInfo, unionType: TypeName): FunSpec {
        val body = CodeBlock.builder().beginControlFlow("when (value)")
        union.members.forEach { member ->
            body.addStatement(
                "is %T -> encoder.encodeSerializableValue(%N, value.value)",
                member.caseClass,
                serializerReference(member),
            )
        }
        body.endControlFlow()
        return FunSpec.builder("serialize")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("encoder", ENCODER)
            .addParameter("value", unionType)
            .addCode(body.build())
            .build()
    }

    private fun deserialize(union: UnionInfo, unionType: TypeName, serializerType: ClassName): FunSpec {
        val body = CodeBlock.builder()
            .addStatement(
                "val input = (decoder as? %T ?: throw %T(%S + decoder::class.simpleName + %S))",
                JSON_DECODER,
                SERIALIZATION_EXCEPTION,
                "${serializerType.simpleName} supports JSON only; got ",
                ".",
            )
            .addStatement("val element = input.decodeJsonElement()")
            .addStatement("val failures = mutableListOf<%T>()", STRING)

        union.members.forEach { member ->
            val reference = serializerReference(member)
            body.beginControlFlow("if (accepts(%N.descriptor, element))", reference)
                .beginControlFlow("try")
                .addStatement("return %T(input.json.decodeFromJsonElement(%N, element))", member.caseClass, reference)
                .nextControlFlow("catch (e: %T)", ILLEGAL_ARGUMENT_EXCEPTION)
                .addStatement("failures += (%S + e.message)", "${member.caseClass.simpleName}: ")
                .endControlFlow()
                .endControlFlow()
        }
        body.addStatement("throw noMatch(element, failures)")

        return FunSpec.builder("deserialize")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("decoder", DECODER)
            .returns(unionType)
            .addCode(body.build())
            .build()
    }

    /** Whether a serializer with this descriptor can produce this JSON value. */
    private fun accepts(): FunSpec = FunSpec.builder("accepts")
        .addModifiers(KModifier.PRIVATE)
        .addParameter("descriptor", SERIAL_DESCRIPTOR)
        .addParameter("element", JSON_ELEMENT)
        .returns(BOOLEAN)
        .addStatement("val kind = (if (descriptor.isInline) descriptor.getElementDescriptor(0) else descriptor).kind")
        .addStatement("if (element is %T) return false", JSON_NULL)
        .addStatement("if (kind == %T.CONTEXTUAL) return true", SERIAL_KIND)
        .beginControlFlow("return when (element)")
        .addStatement(
            "is %T -> (kind == %T.CLASS || kind == %T.OBJECT || kind == %T.MAP || kind is %T)",
            JSON_OBJECT, STRUCTURE_KIND, STRUCTURE_KIND, STRUCTURE_KIND, POLYMORPHIC_KIND,
        )
        .addStatement("is %T -> (kind == %T.LIST)", JSON_ARRAY, STRUCTURE_KIND)
        .beginControlFlow("is %T -> when", JSON_PRIMITIVE)
        .addStatement(
            "element.isString -> (kind == %T.STRING || kind == %T.CHAR || kind == %T.ENUM)",
            PRIMITIVE_KIND, PRIMITIVE_KIND, SERIAL_KIND,
        )
        .addStatement("(element.%M != null) -> (kind == %T.BOOLEAN)", BOOLEAN_OR_NULL, PRIMITIVE_KIND)
        .addStatement(
            "else -> (kind == %T.INT || kind == %T.LONG || kind == %T.SHORT || kind == %T.BYTE || " +
                "kind == %T.FLOAT || kind == %T.DOUBLE)",
            PRIMITIVE_KIND, PRIMITIVE_KIND, PRIMITIVE_KIND, PRIMITIVE_KIND, PRIMITIVE_KIND, PRIMITIVE_KIND,
        )
        .endControlFlow()
        .endControlFlow()
        .build()

    private fun noMatch(union: UnionInfo): FunSpec = FunSpec.builder("noMatch")
        .addModifiers(KModifier.PRIVATE)
        .addParameter("element", JSON_ELEMENT)
        .addParameter("failures", LIST.parameterizedBy(STRING))
        .returns(SERIALIZATION_EXCEPTION)
        .beginControlFlow("val shape = when")
        .addStatement("(element is %T) -> %S", JSON_NULL, "null")
        .addStatement("(element is %T) -> %S", JSON_OBJECT, "an object")
        .addStatement("(element is %T) -> %S", JSON_ARRAY, "an array")
        .addStatement("(element is %T && element.isString) -> %S", JSON_PRIMITIVE, "a string")
        .addStatement("(element is %T && element.%M != null) -> %S", JSON_PRIMITIVE, BOOLEAN_OR_NULL, "a boolean")
        .addStatement("else -> %S", "a number")
        .endControlFlow()
        .addStatement(
            "val detail = (if (failures.isEmpty()) %S + shape else %S + failures.joinToString(%S))",
            "no case accepts ",
            "tried ",
            "; ",
        )
        .addStatement(
            "return %T(%S + shape + %S + detail + %S)",
            SERIALIZATION_EXCEPTION,
            "Cannot decode ",
            " as ${union.unionType.simpleName}: ",
            ".",
        )
        .build()

    private fun serializerOf(type: TypeName): TypeName = K_SERIALIZER.parameterizedBy(type)

    /** The property holding a case's serializer: a constructor property for a type-parameter case. */
    private fun serializerReference(member: UnionMemberInfo): String =
        member.typeParameterName?.let(::parameterSerializerName) ?: "on${member.simpleName}Serializer"

    /** `L` → `lSerializer`. */
    private fun parameterSerializerName(typeParameter: String): String =
        typeParameter.replaceFirstChar(Char::lowercaseChar) + "Serializer"

    private companion object {
        const val SERIALIZATION = "kotlinx.serialization"
        const val DESCRIPTORS = "kotlinx.serialization.descriptors"
        const val JSON = "kotlinx.serialization.json"

        val K_SERIALIZER = ClassName(SERIALIZATION, "KSerializer")
        val SERIALIZATION_EXCEPTION = ClassName(SERIALIZATION, "SerializationException")
        val EXPERIMENTAL_API = ClassName(SERIALIZATION, "ExperimentalSerializationApi")
        val CONTEXTUAL_SERIALIZER = ClassName(SERIALIZATION, "ContextualSerializer")
        val SERIALIZER_FUNCTION = MemberName(SERIALIZATION, "serializer")
        val OPT_IN = ClassName("kotlin", "OptIn")
        val ILLEGAL_ARGUMENT_EXCEPTION = ClassName("kotlin", "IllegalArgumentException")

        val SERIAL_DESCRIPTOR = ClassName(DESCRIPTORS, "SerialDescriptor")
        val SERIAL_DESCRIPTOR_FUNCTION = MemberName(DESCRIPTORS, "SerialDescriptor")
        val SERIAL_KIND = ClassName(DESCRIPTORS, "SerialKind")
        val PRIMITIVE_KIND = ClassName(DESCRIPTORS, "PrimitiveKind")
        val STRUCTURE_KIND = ClassName(DESCRIPTORS, "StructureKind")
        val POLYMORPHIC_KIND = ClassName(DESCRIPTORS, "PolymorphicKind")

        val ENCODER = ClassName("kotlinx.serialization.encoding", "Encoder")
        val DECODER = ClassName("kotlinx.serialization.encoding", "Decoder")

        val JSON_DECODER = ClassName(JSON, "JsonDecoder")
        val JSON_ELEMENT = ClassName(JSON, "JsonElement")
        val JSON_NULL = ClassName(JSON, "JsonNull")
        val JSON_OBJECT = ClassName(JSON, "JsonObject")
        val JSON_ARRAY = ClassName(JSON, "JsonArray")
        val JSON_PRIMITIVE = ClassName(JSON, "JsonPrimitive")
        val BOOLEAN_OR_NULL = MemberName(JSON, "booleanOrNull")
    }
}
