package com.github.fcat97.unionkt.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.ksp.writeTo

/** Emits `<Name>Derived.kt`: `fold` over the direct children plus their accessors. */
internal class DeriveWriter(private val codeGenerator: CodeGenerator, private val emitJvmNames: Boolean) {

    fun write(model: DeriveModel) {
        val file = FileSpec.builder(model.target.packageName, model.fileName)
            .addFileComment("Generated by unionKt from @Derive on %L. Do not edit.", model.target.simpleNames.joinToString("."))
            // A distinctive facade name, so it cannot clash with a user file of the same name. JVM only.
            .apply {
                if (emitJvmNames) {
                    addAnnotation(
                        AnnotationSpec.builder(JvmName::class)
                            .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE)
                            .addMember("%S", model.fileName + "Kt")
                            .build(),
                    )
                }
            }
            .addFunction(fold(model))
        model.cases.forEach { case -> accessors(model, case).forEach(file::addProperty) }

        // Aggregating: a new file may add a new case, which must regenerate the helpers.
        file.build().writeTo(codeGenerator, Dependencies(aggregating = true, *model.sources.toTypedArray()))
    }

    /** `inline fun <R> UiState.fold(onLoading: () -> R, onSuccess: (UiState.Success) -> R, …): R`. */
    private fun fold(model: DeriveModel): FunSpec {
        val result = TypeVariableName(freeTypeVariableName(model.typeVariables.map { it.name }.toSet(), base = "R"))

        val body = CodeBlock.builder().beginControlFlow("return when (this)")
        model.cases.forEach { case ->
            when {
                case.isObject -> body.addStatement("is %T -> %N()", case.checkType, case.handlerName)
                case.needsCast -> body.addStatement("is %T -> %N(this as %T)", case.checkType, case.handlerName, case.typeName)
                else -> body.addStatement("is %T -> %N(this)", case.checkType, case.handlerName)
            }
        }
        body.endControlFlow()

        return FunSpec.builder("fold")
            .addModifiers(strictest(listOf(model.visibility) + model.cases.map { it.visibility }), KModifier.INLINE)
            .apply { if (model.cases.any { it.needsCast }) addAnnotation(suppressUncheckedCast()) }
            .addTypeVariables(model.typeVariables + result)
            .receiver(model.receiver)
            .apply {
                model.cases.forEach { case ->
                    val handler = if (case.isObject) {
                        LambdaTypeName.get(null, emptyList<ParameterSpec>(), result)
                    } else {
                        LambdaTypeName.get(null, case.typeName, returnType = result)
                    }
                    addParameter(case.handlerName, handler)
                }
            }
            .returns(result)
            .addCode(body.build())
            .build()
    }

    /** `val UiState.isSuccess: Boolean` and, except for objects, `val UiState.successOrNull: UiState.Success?`. */
    private fun accessors(model: DeriveModel, case: DeriveCase): List<PropertySpec> {
        val visibility = strictest(listOf(model.visibility, case.visibility))

        val isCase = PropertySpec.builder("is" + case.simpleName, BOOLEAN)
            .addModifiers(visibility)
            .addTypeVariables(model.typeVariables)
            .receiver(model.receiver)
            .getter(FunSpec.getterBuilder().addStatement("return this is %T", case.checkType).build())
            .build()
        if (case.isObject) return listOf(isCase)

        val value = if (case.needsCast) CodeBlock.of("this as %T", case.typeName) else CodeBlock.of("this")
        val orNull = PropertySpec.builder(accessorStem(case.simpleName) + "OrNull", case.typeName.copy(nullable = true))
            .addModifiers(visibility)
            .apply { if (case.needsCast) addAnnotation(suppressUncheckedCast()) }
            .addTypeVariables(model.typeVariables)
            .receiver(model.receiver)
            .getter(
                FunSpec.getterBuilder()
                    .addStatement("return if (this is %T) %L else null", case.checkType, value)
                    .build(),
            )
            .build()
        return listOf(isCase, orNull)
    }

    private fun strictest(visibilities: List<KModifier>): KModifier =
        if (KModifier.INTERNAL in visibilities) KModifier.INTERNAL else KModifier.PUBLIC

    private fun suppressUncheckedCast(): AnnotationSpec =
        AnnotationSpec.builder(Suppress::class).addMember("%S", "UNCHECKED_CAST").build()

    private val DeriveCase.handlerName: String get() = FACTORY_PREFIX + simpleName
}
