package com.github.fcat97.unionkt.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Emits the source file for one [UnionModel].
 *
 * Works purely from the model: every decision about *what* the union contains has
 * already been made by [UnionProcessor] and [MemberResolver].
 */
internal class UnionWriter(private val codeGenerator: CodeGenerator) {

    fun write(model: UnionModel, sources: List<KSFile>) {
        val unionType = model.unionType

        val union = TypeSpec.interfaceBuilder(unionType)
            .addModifiers(model.visibility, KModifier.SEALED)
            .addKdoc(
                "A union of %L.\n\nGenerated from the [%L] marker; `when` over this type is " +
                    "exhaustively checked by the compiler.",
                model.members.joinToString { "[${it.simpleName}]" },
                model.markerName,
            )

        val companion = TypeSpec.companionObjectBuilder()

        model.members.forEach { member ->
            val caseName = CASE_PREFIX + member.simpleName

            union.addType(
                TypeSpec.classBuilder(caseName)
                    .addModifiers(KModifier.DATA)
                    .primaryConstructor(
                        FunSpec.constructorBuilder()
                            .addParameter(VALUE_NAME, member.typeName)
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder(VALUE_NAME, member.typeName)
                            .initializer(VALUE_NAME)
                            .build(),
                    )
                    .addSuperinterface(unionType)
                    .build(),
            )

            companion.addFunction(
                FunSpec.builder(FACTORY_PREFIX + member.simpleName)
                    .addParameter(VALUE_NAME, member.typeName)
                    .returns(unionType)
                    .addStatement("return %T(%N)", unionType.nestedClass(caseName), VALUE_NAME)
                    .build(),
            )
        }

        val fileSpec = FileSpec.builder(unionType)
            .addFileComment("Generated by unionKt from @Union on %L. Do not edit.", model.markerName)
            .addType(union.addType(companion.build()).build())
            .build()

        fileSpec.writeTo(
            codeGenerator = codeGenerator,
            dependencies = Dependencies(aggregating = false, *sources.toTypedArray()),
        )
    }
}
