package com.github.fcat97.unionkt.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.NOTHING
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Emits the source file for one [UnionModel].
 *
 * Works purely from the model: every decision about *what* the union contains has
 * already been made by [UnionProcessor] and [MemberResolver].
 */
internal class UnionWriter(private val codeGenerator: CodeGenerator, private val emitJvmNames: Boolean) {

    fun write(model: UnionModel, sources: List<KSFile>, annotations: List<AnnotationSpec> = emptyList()) {
        val file = FileSpec.builder(model.unionType)
            .addFileComment("Generated by unionKt from @Union on %L. Do not edit.", model.markerName)
            // The top-level helpers below compile into a file facade class. By default it
            // would be `ResultKt`, which clashes with the facade of a user file that is
            // also named `Result.kt` in the same package — a natural home for the marker.
            // Only on the JVM: facade classes exist nowhere else.
            .apply {
                if (emitJvmNames) {
                    addAnnotation(
                        AnnotationSpec.builder(JvmName::class)
                            .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE)
                            .addMember("%S", model.unionType.simpleName + "UnionKt")
                            .build(),
                    )
                }
            }
            .addType(unionInterface(model, annotations))

        constructorFunctions(model).forEach(file::addFunction)
        file.addFunction(fold(model))
        model.members.forEach { member -> accessors(model, member).forEach(file::addProperty) }
        model.flattened.forEach { nested -> file.addFunction(conversion(model, nested)) }

        file.build().writeTo(
            codeGenerator = codeGenerator,
            dependencies = Dependencies(aggregating = false, *sources.toTypedArray()),
        )
    }

    private fun unionInterface(model: UnionModel, annotations: List<AnnotationSpec>): TypeSpec {
        val union = TypeSpec.interfaceBuilder(model.unionType)
            .addModifiers(model.visibility, KModifier.SEALED)
            .addAnnotations(annotations)
            .addTypeVariables(model.typeParameters.map { it.declaredVariable() })
            .addKdoc(
                "A union of %L.\n\nGenerated from the [%L] marker; `when` over this type is " +
                    "exhaustively checked by the compiler.",
                model.members.joinToString { "[${it.simpleName}]" },
                model.markerName,
            )

        val companion = TypeSpec.companionObjectBuilder()
        model.members.forEach { member ->
            union.addType(caseClass(model, member))
            companion.addFunction(factory(model, member))
        }
        return union.addType(companion.build()).build()
    }

    /** `data class OnL<out L>(val value: L) : Either<L, Nothing>`, or `OnInt(...) : Result`. */
    private fun caseClass(model: UnionModel, member: UnionMember): TypeSpec =
        TypeSpec.classBuilder(member.caseName)
            .addModifiers(KModifier.DATA)
            .apply { member.typeParameter?.let { addTypeVariable(it.declaredVariable()) } }
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(VALUE_NAME, member.typeName)
                    .build(),
            )
            .addProperty(
                PropertySpec.builder(VALUE_NAME, member.typeName)
                    .initializer(VALUE_NAME)
                    .build(),
            )
            .addSuperinterface(model.caseSuperType(member))
            .build()

    /** `fun <L> onL(value: L): Either<L, Nothing> = OnL(value)`, inside the companion. */
    private fun factory(model: UnionModel, member: UnionMember): FunSpec =
        FunSpec.builder(member.handlerName)
            .apply { member.typeParameter?.let { addTypeVariable(it.functionVariable()) } }
            .addParameter(VALUE_NAME, member.typeName)
            .returns(model.caseSuperType(member))
            .addStatement("return %T(%N)", model.caseClassName(member), VALUE_NAME)
            .build()

    /**
     * `fun Result(value: Int): Result = Result.OnInt(value)`, one per concrete case.
     *
     * Type-parameter cases get none: `fun <L> Either(value: L)` and `fun <R> Either(value: R)`
     * would share a JVM signature and be ambiguous at every call site.
     */
    private fun constructorFunctions(model: UnionModel): List<FunSpec> =
        model.members.filter { it.typeParameter == null }.map { member ->
            FunSpec.builder(model.unionType.simpleName)
                .addModifiers(model.visibility)
                // Mapped types such as List and MutableList erase to the same JVM type, so
                // every overload gets its own JVM name. Kotlin callers never see it.
                .apply {
                    if (emitJvmNames) {
                        addAnnotation(
                            AnnotationSpec.builder(JvmName::class)
                                .addMember("%S", model.unionType.simpleName + "Of" + member.simpleName)
                                .build(),
                        )
                    }
                }
                .addParameter(VALUE_NAME, member.typeName)
                .returns(model.caseSuperType(member))
                .addStatement("return %T(%N)", model.caseClassName(member), VALUE_NAME)
                .build()
        }

    /**
     * `inline fun <T> Result.fold(onInt: (Int) -> T, …): T`. Every handler is required,
     * so it is as exhaustive as `when`. An extension because an `inline` function with a
     * body cannot be an interface member.
     */
    private fun fold(model: UnionModel): FunSpec {
        val result = TypeVariableName(freeTypeVariableName(model.typeParameters.map { it.name }.toSet()))

        val body = CodeBlock.builder().beginControlFlow("return when (this)")
        model.members.forEach { member ->
            body.addStatement("is %T -> %N(%N)", model.caseClassName(member), member.handlerName, VALUE_NAME)
        }
        body.endControlFlow()

        return FunSpec.builder("fold")
            .addModifiers(model.visibility, KModifier.INLINE)
            .addTypeVariables(model.typeParameters.map { it.functionVariable() } + result)
            .receiver(model.selfType())
            .apply {
                model.members.forEach { member ->
                    addParameter(member.handlerName, LambdaTypeName.get(null, member.typeName, returnType = result))
                }
            }
            .returns(result)
            .addCode(body.build())
            .build()
    }

    /** `val Result.isInt: Boolean` and `val Result.intOrNull: Int?`. */
    private fun accessors(model: UnionModel, member: UnionMember): List<PropertySpec> {
        val caseClass = model.caseClassName(member)
        val typeVariables = model.typeParameters.map { it.functionVariable() }

        val isCase = PropertySpec.builder("is" + member.simpleName, BOOLEAN)
            .addModifiers(model.visibility)
            .addTypeVariables(typeVariables)
            .receiver(model.selfType())
            .getter(FunSpec.getterBuilder().addStatement("return this is %T", caseClass).build())
            .build()

        val orNull = PropertySpec.builder(accessorStem(member.simpleName) + "OrNull", member.typeName.copy(nullable = true))
            .addModifiers(model.visibility)
            .addTypeVariables(typeVariables)
            .receiver(model.selfType())
            .getter(
                FunSpec.getterBuilder()
                    .addStatement("return if (this is %T) %N else null", caseClass, VALUE_NAME)
                    .build(),
            )
            .build()

        return listOf(isCase, orNull)
    }

    /**
     * `fun Shape.toItem(): Item`, mapping each of the flattened union's cases onto the
     * same-typed case here. Visibility is the stricter of the two unions; a generic
     * union's conversion returns `Item<Nothing, …>`, which covariance makes assignable
     * to any parameterisation.
     */
    private fun conversion(model: UnionModel, nested: FlattenedUnion): FunSpec {
        val body = CodeBlock.builder().beginControlFlow("return when (this)")
        nested.members.forEach { member ->
            body.addStatement(
                "is %T -> %T(%N)",
                nested.unionType.nestedClass(member.caseName),
                model.caseClassName(member),
                VALUE_NAME,
            )
        }
        body.endControlFlow()

        val visibility =
            if (model.visibility == KModifier.INTERNAL || nested.visibility == KModifier.INTERNAL) {
                KModifier.INTERNAL
            } else {
                KModifier.PUBLIC
            }

        return FunSpec.builder("to" + model.unionType.simpleName)
            .addModifiers(visibility)
            .receiver(nested.unionType)
            .returns(model.nothingType())
            .addCode(body.build())
            .build()
    }
}

// Naming and typing helpers shared by every emitter in this file.

private val UnionMember.caseName: String get() = CASE_PREFIX + simpleName

/** The `on<Case>` name used by companion factories and `fold` parameters. */
private val UnionMember.handlerName: String get() = FACTORY_PREFIX + simpleName

private fun UnionModel.caseClassName(member: UnionMember): ClassName =
    unionType.nestedClass(member.caseName)

private fun UnionModel.parameterized(argument: (UnionTypeParameter) -> TypeName): TypeName =
    if (typeParameters.isEmpty()) unionType else unionType.parameterizedBy(typeParameters.map(argument))

/** `Either<L, R>`: the union over its own type variables, the receiver of every helper. */
private fun UnionModel.selfType(): TypeName = parameterized { TypeVariableName(it.name) }

/** `Either<Nothing, Nothing>`: what a concrete case is, and what conversions return. */
private fun UnionModel.nothingType(): TypeName = parameterized { NOTHING }

/** `Either<L, Nothing>` for the `L` case; [nothingType] for a concrete case. */
private fun UnionModel.caseSuperType(member: UnionMember): TypeName =
    parameterized { if (it == member.typeParameter) TypeVariableName(it.name) else NOTHING }

/** As declared on a function or extension property, where variance is not allowed. */
private fun UnionTypeParameter.functionVariable(): TypeVariableName =
    TypeVariableName(name, bounds)
