package com.github.fcat97.unionkt.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.NOTHING
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Emits the source file for one [UnionModel].
 *
 * Works purely from the model: every decision about *what* the union contains has
 * already been made by [UnionProcessor] and [MemberResolver].
 */
internal class UnionWriter(private val codeGenerator: CodeGenerator) {

    fun write(model: UnionModel, sources: List<KSFile>) {
        val file = FileSpec.builder(model.unionType)
            .addFileComment("Generated by unionKt from @Union on %L. Do not edit.", model.markerName)
            .addType(unionInterface(model))

        file.build().writeTo(
            codeGenerator = codeGenerator,
            dependencies = Dependencies(aggregating = false, *sources.toTypedArray()),
        )
    }

    private fun unionInterface(model: UnionModel): TypeSpec {
        val union = TypeSpec.interfaceBuilder(model.unionType)
            .addModifiers(model.visibility, KModifier.SEALED)
            .addTypeVariables(model.typeParameters.map { it.declaredVariable() })
            .addKdoc(
                "A union of %L.\n\nGenerated from the [%L] marker; `when` over this type is " +
                    "exhaustively checked by the compiler.",
                model.members.joinToString { "[${it.simpleName}]" },
                model.markerName,
            )

        val companion = TypeSpec.companionObjectBuilder()
        model.members.forEach { member ->
            union.addType(caseClass(model, member))
            companion.addFunction(factory(model, member))
        }
        return union.addType(companion.build()).build()
    }

    /** `data class OnL<out L>(val value: L) : Either<L, Nothing>`, or `OnInt(...) : Result`. */
    private fun caseClass(model: UnionModel, member: UnionMember): TypeSpec =
        TypeSpec.classBuilder(member.caseName)
            .addModifiers(KModifier.DATA)
            .apply { member.typeParameter?.let { addTypeVariable(it.declaredVariable()) } }
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(VALUE_NAME, member.typeName)
                    .build(),
            )
            .addProperty(
                PropertySpec.builder(VALUE_NAME, member.typeName)
                    .initializer(VALUE_NAME)
                    .build(),
            )
            .addSuperinterface(model.caseSuperType(member))
            .build()

    /** `fun <L> onL(value: L): Either<L, Nothing> = OnL(value)`, inside the companion. */
    private fun factory(model: UnionModel, member: UnionMember): FunSpec =
        FunSpec.builder(member.handlerName)
            .apply { member.typeParameter?.let { addTypeVariable(it.functionVariable()) } }
            .addParameter(VALUE_NAME, member.typeName)
            .returns(model.caseSuperType(member))
            .addStatement("return %T(%N)", model.caseClassName(member), VALUE_NAME)
            .build()
}

// Naming and typing helpers shared by every emitter in this file.

private val UnionMember.caseName: String get() = CASE_PREFIX + simpleName

/** The `on<Case>` name used by companion factories and `fold` parameters. */
private val UnionMember.handlerName: String get() = FACTORY_PREFIX + simpleName

private fun UnionModel.caseClassName(member: UnionMember): ClassName =
    unionType.nestedClass(member.caseName)

private fun UnionModel.parameterized(argument: (UnionTypeParameter) -> TypeName): TypeName =
    if (typeParameters.isEmpty()) unionType else unionType.parameterizedBy(typeParameters.map(argument))

/** `Either<L, R>`: the union over its own type variables, the receiver of every helper. */
private fun UnionModel.selfType(): TypeName = parameterized { TypeVariableName(it.name) }

/** `Either<Nothing, Nothing>`: what a concrete case is, and what conversions return. */
private fun UnionModel.nothingType(): TypeName = parameterized { NOTHING }

/** `Either<L, Nothing>` for the `L` case; [nothingType] for a concrete case. */
private fun UnionModel.caseSuperType(member: UnionMember): TypeName =
    parameterized { if (it == member.typeParameter) TypeVariableName(it.name) else NOTHING }

/** As declared on the union and on its case class: always `out`, bounds kept. */
private fun UnionTypeParameter.declaredVariable(): TypeVariableName =
    TypeVariableName(name, bounds, KModifier.OUT)

/** As declared on a function or extension property, where variance is not allowed. */
private fun UnionTypeParameter.functionVariable(): TypeVariableName =
    TypeVariableName(name, bounds)
